Single weather report view work
JackMcKill/CP3407-Project pull request #30
Opened 2021-10-01 06:12 UTC by calebwebster

# Overview

This PR will complete the basic layout of the SingleWeatherReport activity.

The format of the activity is an exact replication of the example user story wireframe and contains placeholder values and images.

## Changes

- Changes to xml file
- Comment out findViewById() calls to avoid errors, as the new xml views have not been assigned IDs yet.
- Add a few new .png image files for placeholders
- New drawable city_name_layout_bg.xml file for the blue background of the LinearLayout that displays the city name and state abbreviation.

## Notes

### ToDo:

- Data insertion needs to be done.
- Buttons need to be hooked up
- Weather data fields may need to be changed (I'm not sure if the data we have matches the wireframe fields, I literally just copied the wireframe)
- Probably an animation for the data drop-down with the little chevron button next to the "Details" text

_Important_: Free images from [Flaticon](https://www.flaticon.com) were used, and authors need to be attributed:

<div>Icons made by <a href="https://www.flaticon.com/authors/vignesh-oviyan" title="Vignesh Oviyan">Vignesh Oviyan</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></div>

<div>Icons made by <a href="https://www.flaticon.com/authors/fps-web-agency" title="fps web agency">fps web agency</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></div>

<div>Icons made by <a href="https://www.flaticon.com/authors/good-ware" title="Good Ware">Good Ware</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></div>

<div>Icons made by <a href="https://www.freepik.com" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></div>

<div>Icons made by <a href="https://www.freepik.com" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></div>

<div>Icons made by <a href="https://www.flaticon.com/authors/mavadee" title="mavadee">mavadee</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></div>

2021-10-01 07:13 UTC, JackMcGill requested changes

2021-10-01 07:13 UTC, JackMcGill commented on app/src/main/res/layout/activity_single_weather_report.xml
> +                android:id="@+id/textView4"
Hi @CalebWebsterJCU, the screenshots you sent of the layout look spot on, good work. 

As I can’t compile and run the project I can’t give you a full review, that will have to come from someone else who can run your code. From what I can see though, your XML view properties have non-descriptive names, so they will be hard to work with when they’re being accessed by the Java code. Check our [contributing](https://github.com/JackMcKill/CP3407-Project/blob/develop/Contributing.md) page to see more info on naming, but the names should be something more along these lines: 
```suggestion
                android:id="@+id/tv_maxTemp"
```

2021-10-01 07:14 UTC, JackMcGill commented on app/src/main/res/layout/activity_single_weather_report.xml
> +                android:id="@+id/textView4"
Apart from the property names, everything else looks really good that I can see. Nice work

2021-10-01 07:28 UTC, HarperThurlow commented
I am getting a "AAPT: error: resource drawable/ic_barometer (aka com.cp3407.wildernessweather:drawable/ic_barometer) not found." error when trying to run your code. My guess is that something that you have used in your code is not saved in the actual project structure and locally on your computer (probably ic_barometer). This might not be the only one but is the only one I can see for now.

2021-10-01 07:32 UTC, calebwebster commented on app/src/main/res/layout/activity_single_weather_report.xml
> +                android:id="@+id/textView4"
Thanks, I will update the names.

2021-10-01 07:34 UTC, calebwebster commented
@HarperThurlow I also noticed that the barometer image (thats what it is) was not contained in the PR. I'll see if I can sort it out.

2021-10-01 07:34 UTC, HarperThurlow commented
Another thing I am noticing is you have very set in stone widths. This wont be good for if someone is using anothe device (either bigger or smaller). To fix this we normally use Percentages instead of exact dp measurements. 
Also what Jack has said above is super important as it makes better documentation too so we know what button/image/textview is what. Wouldn't hurt to add some small comments saying what it is within the object aswell.

2021-10-01 08:05 UTC, calebwebster commented
I'm changing everything over to percentages, would you advise dividing the LinearLayouts into parts using weightSum, or treating it as one part, with the widgets occupying a percentage of that one part?

2021-10-01 08:13 UTC, HarperThurlow commented
Not quiet sure what you mean. Wanna jump on a call on discord?

2021-10-01 08:14 UTC, calebwebster commented
Ok I just learned that weightSum is the sum of the weights of all its widgets, I've set weightSum to 100 so that everything inside can be a percentage value for the layout_weight.

2021-10-01 08:39 UTC, calebwebster commented
Finished converting to percentages.

2021-10-06 09:12 UTC, JackMcGill approved these changes

2021-10-06 09:22 UTC, JackMcGill commented
Thanks for making those changes @CalebWebsterJCU, it's looking good. Before you merge this branch however, we should probably decide what we are going to do about the `AppBar` + the blue bar that's going on:  

<img width="369" alt="Screen Shot 2021-10-06 at 7 16 07 pm" src="https://user-images.githubusercontent.com/14053993/136175013-9bf7b3ad-c557-43fe-8d82-5171700bb4a4.png">. 

 Currently it looks a bit cluttered to me, having first the `AppBar` and then directly underneath it basically another one.
 
 I propose we get rid of the blue bar in the XML layout file, and instead program our `AppBar` itself to be blue and display the city name (rather than saying WildernessWeather), along with a left-facing chevron to work as a "back button" or "up button". What do you think @CalebWebsterJCU? 

There is an example of how to change the text displayed in the `AppBar` on the `SettingsActivity` file. You can very easily set the text (and I imagine colour as well) for it in the `onCreate` method.

2021-10-07 03:25 UTC, HarperThurlow approved these changes
Thanks for fixing those issues @CalebWebsterJCU. All looks good to me now 👍

2021-10-08 03:42 UTC, merged