Homescreen GUI
JackMcKill/CP3407-Project pull request #31
Opened 2021-10-06 06:09 UTC by CarolineYHao

## Overview
This PR will complete the basic layout of the Home screen GUI
The format of the activity is an exact replication of the example user story wireframe.
### Changes
•	Changes to xml file
•	Comment out findViewById() calls to avoid errors, as the new xml views have not been assigned IDs yet.
•	Added Metaweather icons for weather status
•	New bg_home.xml file for the gradient background.
### ~~ToDo:~~
•	~~Figure out how extra locations are added - recycler view~~
•	~~Insert data~~
•	~~Link buttons~~

_Weather icons downloaded from Metaweather API website
Settings icon from icons8.com_

## Notes
I've (@JackMcKill) taken over this PR and related issues from @CarolineYHao. My latest commits add a list view that displays the weather for the users "favourite" locations. It takes a second or 2 to load upon startup as it has to make several API calls to [metaweather.com](https://www.metaweather.com). I've also add searching functionality to the search bar, which takes the user to the `APIactivity` and displays a list of weather reports for the searched location.
This PR closes #4

2021-10-07 01:09 UTC, JackMcGill commented on app/src/main/java/com/cp3407/wildernessweather/MainActivity.java
> +//        dbPrototype = findViewById(R.id.dbPrototype);
This can be removed, no need for these anymore 😄 
```suggestion
```
You can also remove the declarations at the top of the file, lines 17 + 18: 
```java
Button apiPrototype;
Button dbPrototype;
```

2021-10-07 01:21 UTC, JackMcGill commented on app/src/main/res/layout/activity_main.xml
>      <androidx.constraintlayout.widget.ConstraintLayout
This constraint layout here should be replaced by a `listView` which should display a list of locations.

2021-10-07 01:38 UTC, JackMcGill requested changes
Hi @CarolineYHao, this is all looking really good, there's just a couple small things that should be changed before merging.

Most importantly, the `constraintLayout` on lines 58 -> 111 should be replaced with a `listView`, and that `listView` should display a list of those `constraintLayouts`. I've created a new issue (#32) for this, so it's up to you whether you want to tackle that now and put it into this PR, or just change to a `listView` and merge now, then work on #32 later.

Finally, there are some merge conflicts between this branch and `develop` that need to be resolved before the merge can happen. Once you've made your changes, you'll have to perform a merge commit locally that resolves the problems. This is relatively simple to do using the GitHub Desktop application - just let me know if you want any help with it.

2021-10-07 01:43 UTC, JackMcGill commented on app/src/main/res/layout/activity_main.xml
>      <androidx.constraintlayout.widget.ConstraintLayout
@CarolineYHao ignore the code box showing changes above, not sure why but GitHub is showing the wrong block of code here. I'm referring to the `constraintLayout` on line 58. My comment below goes into more detail.

2021-10-08 03:40 UTC, HarperThurlow commented on app/src/main/res/layout/activity_main.xml
> +            android:id="@+id/LowTemp"
@CarolineYHao Small change but things with this text view need tv_lowTemp. Our Contributing.md file has more of these in place.
When having these we also need to make sure they aren't the same in multiple places. So where @CalebWebsterJCU has put tv_lowTemp we need to make sure that it is different. A simple "HS_tv_lowTemp" will work.

2021-10-20 21:54 UTC, calebwebster approved these changes

2021-10-28 04:44 UTC, HarperThurlow requested changes
Couple of issues I found while testing:
- When you type a search query on the main screen and press search, it doesn't add the search to the new activity and instantly search. This feature would be good to minimize user presses. 
P.S. After more testing i found if you just click the "Press for weather Data" button it does get the city you placed in. All that needs to be done is instant search and populate the search field
- Settings doesn't open settings activity (I think this is because it wasn't rebased but thats ok we can do that later)
- The get date isn't showing on the main screen (Can be seperated into another issue)
- I see you have code there ready for favourites to show but just not implemented yet so thats ok

2021-10-28 21:53 UTC, JackMcGill commented
Thanks for that @HarperThurlow, will merge now

2021-10-28 22:15 UTC, merged