Download and Export CSV
JackMcKill/CP3407-Project pull request #44
Opened 2021-10-19 06:19 UTC by HarperThurlow

This PR allows the user to download .csv file of the SingleWeatherReport and make it possible to share using Android Share Sheet.

Currently the file location is hard-coded to appear in our folder for the application. This can be changed upon a later review or if we want it saved somewhere else (However must be coded and is not dynamic).

If reviewers can please checkout this branch to test if everything is running smoothly that would be great :)

2021-10-19 11:24 UTC, JackMcGill requested changes
I think this PR is _almost_ ready to go. Before it's merged into `develop` however I think that we should do 2 things:

1. The button icon used to create and share the CSV file is currently a "download" button. I think this should be changed to a generic "Share" icon, as I feel this better suits the action that takes place when this button is pressed.
2. There have been updates to the properties inside `WeatherReportModel`, specifically there is now a `woeid` property. Therefore the code that creates the CSV should probably be updated to reflect this. This can be done by either rebasing this branch onto `develop`, or perhaps an easier solution, is to just replace the contents of `WeatherReportModel` with the version on the `develop` branch.

Both these changes are minor and I'm happy to help implement both if you agree with them.
Otherwise everything else looks good to me, and is otherwise ready to merge 😄

2021-10-19 11:24 UTC, JackMcGill commented on app/src/main/java/com/cp3407/wildernessweather/ExportCSV.java
> +    /*
Maybe move this link to the ExportCSV documentation page, with a brief description of the `super-csv` dependancy.
**Edit-** I'm actually referencing the link on line `17`, looks like I have highlighted the wrong lines in this comment.

2021-10-20 01:22 UTC, HarperThurlow commented on app/src/main/java/com/cp3407/wildernessweather/ExportCSV.java
> +    /*
Ya documentation does need a bit of work for sure. I'll throw a small talk about the dependency now :)

2021-10-20 21:53 UTC, calebwebster approved these changes
Looks good.

2021-10-21 04:53 UTC, JackMcGill commented on app/src/main/java/com/cp3407/wildernessweather/ExportCSV.java
> +    /*
👍

2021-10-21 08:10 UTC, JackMcGill approved these changes
Good to go now.

2021-10-21 08:11 UTC, merged